name: Deploy Product Queries

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'
            
            - name: Enter the microservice folder
              run: cd acme

            - name: Build project
              working-directory: ./acme
              run: mvn clean install -DskipTests
            
            - name: Login Docker Hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

            - name: Build docker image
              working-directory: ./acme
              run: docker build -t viniciuskuchnir20/acme_products_queries .
              
            - name: Push image docker
              run: docker push viniciuskuchnir20/acme_products_queries